# Generated by Django 4.2.4 on 2023-09-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_photo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Meep',
        ),
    ]
