# Generated by Django 4.2.4 on 2023-09-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_photo_comment_alter_photo_caption_delete_meep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
