# Generated by Django 4.2.4 on 2023-09-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_photo_delete_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
